/**
 * Compiles src/seatMapTemplate.html into the CDN-hosted widget shell:
 *   dist/seatmap-shell.min.js
 *
 * The shell is everything that never changes between requests — the minified
 * CSS, the static page skeleton, and the render/pan/zoom/scoring JS — packed
 * into one self-installing script. At runtime it injects the CSS, mounts the
 * skeleton where the loading line sits, and runs the widget logic, which
 * reads its per-request data from the #cinema-data JSON island that
 * buildSeatMapWidget() emits alongside the <script src>.
 *
 * seatMapTemplate.html stays the single source of truth: edit it, run
 *   npm run build:shell
 * then follow the release checklist in RELEASING.md (bump SHELL_VERSION, tag,
 * push) so jsDelivr serves the new shell.
 *
 * This script refuses to overwrite the shell when the content changed but
 * SHELL_VERSION did not — see checkVersionBump below for why that matters.
 */
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";
import { MINIFIED_TEMPLATE, SHELL_VERSION } from "../src/seatMapTemplate.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "dist");
export const SHELL_PATH = join(OUT_DIR, "seatmap-shell.min.js");
export const MANIFEST_PATH = join(OUT_DIR, "shell-manifest.json");

/**
 * Compare and hash line-ending-insensitively. Git can check this file out
 * with CRLF on Windows, and CI runs on Linux — without this, the drift test
 * would fail on a platform difference that has nothing to do with the code.
 */
export const normalizeEol = (s) => String(s).replace(/\r\n/g, "\n");

export const shellHash = (content) =>
  createHash("sha256").update(normalizeEol(content)).digest("hex");

/** Assemble the shell from the template. Pure — writes nothing. */
export function buildShell() {
  const css = (MINIFIED_TEMPLATE.match(/<style>([\s\S]*?)<\/style>/) ?? [])[1];
  // The main logic block is the only bare <script> (the data island's tag
  // carries id/type attributes, so this regex skips it).
  const js = (MINIFIED_TEMPLATE.match(/<script>([\s\S]*?)<\/script>/) ?? [])[1];
  // Static skeleton: the markup between the style block and the data island.
  const staticHtml = MINIFIED_TEMPLATE
    .split("</style>")[1]
    ?.split('<script id="cinema-data"')[0]
    ?.trim();

  if (!css || !js || !staticHtml) {
    throw new Error("build-shell: failed to parse seatMapTemplate.html into css/js/skeleton parts");
  }

  return `/* cineplex-mcp seat-map widget shell ${SHELL_VERSION} — generated by scripts/build-shell.mjs, do not edit */
(function () {
  "use strict";
  var style = document.createElement("style");
  style.textContent = ${JSON.stringify(css)};
  document.head.appendChild(style);
  var mount = document.createElement("div");
  mount.innerHTML = ${JSON.stringify(staticHtml)};
  var loading = document.getElementById("cinema-loading");
  if (loading) { loading.replaceWith(mount); } else { document.body.appendChild(mount); }
${js}
})();
`;
}

export function readManifest() {
  if (!existsSync(MANIFEST_PATH)) return null;
  try {
    return JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
  } catch {
    return null;
  }
}

/**
 * Guard against the one mistake this setup makes easy and silent.
 *
 * jsDelivr serves the shell from a git tag with `max-age=604800` (7 days) and
 * no revalidation, so re-pointing a published tag does NOT reliably reach
 * clients. If the template changes while SHELL_VERSION stays put, everything
 * looks fine locally — the preview uses the local file — but real widgets keep
 * loading the OLD shell from the OLD tag for up to a week, with no error
 * anywhere.
 *
 * So: content changed + version unchanged = hard stop.
 *
 * @returns {{ ok: true } | { ok: false, message: string }}
 */
export function checkVersionBump(content, manifest = readManifest()) {
  if (!manifest) return { ok: true }; // first build; nothing to compare against
  if (manifest.version !== SHELL_VERSION) return { ok: true }; // version bumped
  if (manifest.sha256 === shellHash(content)) return { ok: true }; // nothing changed

  return {
    ok: false,
    message:
      `The widget shell changed but SHELL_VERSION is still "${SHELL_VERSION}".\n\n` +
      `jsDelivr serves that tag with a 7-day cache and no revalidation, so re-pointing it\n` +
      `does not reliably reach clients — shipping this would leave widgets on the old shell.\n\n` +
      `Bump SHELL_VERSION in src/seatMapTemplate.js, then rebuild. See RELEASING.md.\n` +
      `(Use --force to rebuild anyway for local experiments.)`,
  };
}

function main() {
  const force = process.argv.includes("--force");
  const shell = buildShell();

  const check = checkVersionBump(shell);
  if (!check.ok && !force) {
    console.error(`build-shell: ${check.message}`);
    process.exitCode = 1;
    return;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(SHELL_PATH, shell);
  writeFileSync(
    MANIFEST_PATH,
    JSON.stringify({ version: SHELL_VERSION, sha256: shellHash(shell) }, null, 2) + "\n"
  );

  console.log(`Built ${SHELL_PATH} (${(shell.length / 1024).toFixed(0)} KB, shell version ${SHELL_VERSION})`);
  if (force && !check.ok) {
    console.warn("build-shell: WARNING — rebuilt with --force despite an unchanged SHELL_VERSION. Do not publish this.");
  }
}

// Only build when run as a script; importing this module (tests do) must not
// write files.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
