/**
 * Compiles src/seatMapTemplate.html into the CDN-hosted widget shell:
 *   dist/seatmap-shell.min.js
 *
 * The shell is everything that never changes between requests — the minified
 * CSS, the static page skeleton, and the render/pan/zoom/scoring JS — packed
 * into one self-installing script. At runtime it injects the CSS, mounts the
 * skeleton where the loading line sits, and runs the widget logic, which
 * reads its per-request data from the #cinema-data JSON island that
 * buildSeatMapWidget() emits alongside the <script src>.
 *
 * seatMapTemplate.html stays the single source of truth: edit it, run
 *   npm run build:shell
 * then follow the version-bump procedure documented on SHELL_VERSION in
 * src/seatMapTemplate.js (new tag, push) so jsDelivr serves the new shell.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { MINIFIED_TEMPLATE, SHELL_VERSION } from "../src/seatMapTemplate.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "dist");
const OUT = join(OUT_DIR, "seatmap-shell.min.js");

const css = (MINIFIED_TEMPLATE.match(/<style>([\s\S]*?)<\/style>/) ?? [])[1];
// The main logic block is the only bare <script> (the data island's tag
// carries id/type attributes, so this regex skips it).
const js = (MINIFIED_TEMPLATE.match(/<script>([\s\S]*?)<\/script>/) ?? [])[1];
// Static skeleton: the markup between the style block and the data island.
const staticHtml = MINIFIED_TEMPLATE
  .split("</style>")[1]
  ?.split('<script id="cinema-data"')[0]
  ?.trim();

if (!css || !js || !staticHtml) {
  throw new Error("build-shell: failed to parse seatMapTemplate.html into css/js/skeleton parts");
}

const shell = `/* cineplex-mcp seat-map widget shell ${SHELL_VERSION} — generated by scripts/build-shell.mjs, do not edit */
(function () {
  "use strict";
  var style = document.createElement("style");
  style.textContent = ${JSON.stringify(css)};
  document.head.appendChild(style);
  var mount = document.createElement("div");
  mount.innerHTML = ${JSON.stringify(staticHtml)};
  var loading = document.getElementById("cinema-loading");
  if (loading) { loading.replaceWith(mount); } else { document.body.appendChild(mount); }
${js}
})();
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, shell);
console.log(`Built ${OUT} (${(shell.length / 1024).toFixed(0)} KB, shell version ${SHELL_VERSION})`);
